### PR TITLE
added support for W3C Geolocation API properties

### PR DESCRIPTION
**Pull request by cordovapolymer**
added support for properties following [W3C naming](https://dev.w3.org/geo/api/spec-source.html)
```
altitudes
accuracies
altitudeAccuracies
headings
speeds
```
preserved support for `coordTimes` for backward compatibility. 
Output is now cleaner, no more null values when `coordTimes` is empty.

### CODE REVIEW

**Comment by tmcw** [comment]
I don't follow the reasoning behind this change. If we want to preserve properties, why wouldn't we preserve all properties? The W3C geolocation API, while a very nice API, has no formal relationship with stored data, GeoJSON, or this codebase, and I don't see any reason why it would be an authoritative example to follow.

**Comment by cordovapolymer** [comment]
It's a good practice to follow common naming. GeoJSON specification itself follows W3C [JSON-LD 1.0](https://www.w3.org/TR/json-ld/).

> If we want to preserve properties, why wouldn't we preserve all properties? 

Go ahead, it would be perfect if geojson-tidy would preserve all properties, and filter out specified arrays (such as timestamps, accuracies, etc.).

**Comment by tmcw** [comment]
> GeoJSON specification itself follows W3C JSON-LD 1.0.

The [geojson-ld](https://github.com/geojson/geojson-ld) proposal is just a proposal, and is an extension of, not a replacement for, GeoJSON. The [GeoJSON specification](https://tools.ietf.org/html/rfc7946) uses JSON, not JSON-LD, and JSON is an [IETF standard](https://tools.ietf.org/html/rfc7159), not a W3C Standard.

**Comment by tmcw** [comment]
Closing; this subset of properties has no importance in GeoJSON land. Would accept a PR that optionally includes _all_ properties from the input set.

**Pull request closed without merging**
